# Generated by Django 3.1.14 on 2022-03-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0004_auto_20220309_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
