# Generated by Django 3.1.14 on 2022-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0005_auto_20220309_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
