# Generated by Django 3.1.14 on 2022-03-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubsshop', '0002_auto_20220310_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
